# Generated by Django 5.2.3 on 2025-07-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_productid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sku'], 'verbose_name': 'product variant', 'verbose_name_plural': 'product variants'},
        ),
    ]
